controller:
  numExecutors: 0
  installLatestPlugins: true
  installLatestSpecifiedPlugins: true
  overwritePlugins: true
  installPlugins:
    - kubernetes
    - workflow-aggregator
    - git
    - configuration-as-code
    - credentials-binding
    - pipeline-stage-view
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: "2"
      memory: 3Gi
  sidecars:
    configAutoReload:
      enabled: false

agent:
  enabled: true
  namespace: jenkins
  jenkinsUrl: http://jenkins.jenkins.svc.cluster.local:8080
  websocket: true

persistence:
  enabled: true
  storageClass: standard
  size: 8Gi
